### PR TITLE
Person lineage

### PR DESCRIPTION
**Pull request by azurebrd**
Added js.cytoscape lineage view to Lineage widget in Person page, for Raymond and Cecilia.

### CODE REVIEW

**Comment by sibyl229** [comment]
Hi @azurebrd I noticed the ancestors_data field returns a lot of HTML. It's generally advised to return only the data from the REST API (.pm file), and feed them through the template (.tt2) to generate the HTML. This way, when you are ready to pull data from Datomic, your view will work with it without modification. Is there a particular reason you are doing it the current way? Thanks!

**Comment by azurebrd** [comment]
Thanks for pointing it out, Sibyl, I've cleaned that up.

**Comment by raymond91125** [comment]
YEAH!

**Comment by sibyl229** [comment]
Thanks @azurebrd ! I was playing with Datomic query yesterday, this query finds Paul's students:
```
[:find ?sname
 :where
 [?e :person/id "WBPerson625"]
 [?sh :person.supervised-by/person ?e]
 [?s :person/supervised-by ?sh]
 [?s :person/full-name ?sname]
]
```
The  ":find ?sname" can be replaced with ":find (count ?sname)" to count Paul's direct students. There are 80!!!

This following query will count the Paul's indirect students 5 hops away, it seems perform really well (I don't know if there's a easier way to construct the query, if you figure out one, please let me know :) ):
```
[:find (count ?sname)
 :where
 [?e :person/id "WBPerson625"]
 [?sh :person.supervised-by/person ?e]
 [?s :person/supervised-by ?sh]
 [?sh1 :person.supervised-by/person ?s]
 [?s1 :person/supervised-by ?sh1]
 [?sh2 :person.supervised-by/person ?s1]
 [?s2 :person/supervised-by ?sh2]
 [?sh3 :person.supervised-by/person ?s2]
 [?s3 :person/supervised-by ?sh3]
 [?sh4 :person.supervised-by/person ?s3]
 [?s4 :person/supervised-by ?sh4]
 [?s4 :person/full-name ?sname]
]
```

**Comment by mgrbyte** [comment]
@sibyl229 @azurebrd I think they key to expressing recusrive/graph type queries like this is to use rules.
Check out [this][https://gist.github.com/jonase/3122363] and [this][https://github.com/Datomic/mbrainz-sample/blob/master/src/clj/datomic/samples/mbrainz/rules.clj] for examples.

**Comment by sibyl229** [comment]
@mgrbyte Thanks a lot! This is exactly the thing we need. Is it me, or this thing basically lets us write Prolog with all the facts in the database? :-)

**Comment by azurebrd** [comment]
Thanks @sibyl229 for the merge and looking into the query.
Thanks @mgrbyte for the pointer at a deeper way of querying.

**Comment by raymond91125** [comment]
@mgrbyte Interesting!

**Comment by khowe** [comment]
@azurebrd Yes, exactly that.

**Pull request merged**
