### PR TITLE
Inferred Tree format now uniform between ancestors and children

### PR DESCRIPTION
**Pull request by azurebrd**
Thanks Sybil, for being so quick about pulling it last time =)

### CODE REVIEW

**Comment by raymond91125** [comment]
per @chris-grove suggestion of making indentation consistent in the inferred tree view of ontology browser widget. e.g. species/all/go_term/GO:0042446#02--10

**Comment by raymond91125** [comment]
bump

**Comment by sibyl229** [comment]
Thanks :) Merged to staging. Shall I include this for the WS249 web release this weekend?
The search index is rebuilding right now, so the staging site isn't functional. But you should be able to check it on staging tomorrow.

**Comment by raymond91125** [comment]
yes, please include for WS249 if possible. thanks.

**Comment by sibyl229** [comment]
Sure. No problem.

**Comment by azurebrd** [comment]
Thanks @sibyl229

**Pull request merged**
