### PR TITLE
fpkm plot based on selected modENCODE libraries

### PR DESCRIPTION
**Pull request by sibyl229**
Hi @gw3 no problem, you know the best about your data. I fixed most things you brought up:
- column width
- sub-sections section label
- more space on x-axis between subsections 
- horizontal x-axis label

As for color, this time I try to keep it similar to what you had, but the base rbg colors aren't great for making good looking plots. So I choose diverging color palette (http://colorbrewer2.org/) that uses purple and green for the ribozero and polyA. Diverging palette is for displaying contrast between two datasets. You don't see green and blue in diverging palettes there, because for the kind of green and blue that looks nice on a plot they would end up look too similar to each other.

Could you send me a screenshot of the font problem you see? And please let me know what browser and operating system you are using.

screen shot 2015-12-16 at 6 37 57 pm

### CODE REVIEW

**Comment by gw3** [comment]
Hi @sibyl229,

I was using Firefox 38.2.1 on RedHat Linux.
I can't get staging to display at present (it times out), so I can't see what it looks like now, but attached is a screen-shot of what it looked like yesterday.
jagraph


Colours look much better now.
My son looked at the orange/green colours you had been using and couldn't easily see a difference (he is colour-blind).
I think there is no problem now.

I like the changes.

The grey histograms in the example you mailed to me are sometimes slightly off-center when compared to the axis-ticks and the data points. This is particularly noticeable in the Embryonic time-series sub-section, but also in places like EE, L2 and the Dauer stages.

Could you make the graphs higher? 
I had the width of the plotting area of the graph about 2.5 times the height.
You currently have the width about 4 times the height.

The text looks faint. Are you using a grey colour for the text? Could you use black?

**Comment by gw3** [comment]
Could you put the class and ID of the object being displayed in the title?

**Comment by gw3** [comment]
Hi @sibyl229,

It has been pointed out that the modENCODE expression graph is being displayed as an empty graph in non-elegans species. 

Could the graph not be displayed in non-elegans species, please?

Is there any progress on the points raised in this issue from a month ago?
(Use black text instead of grey, make the graph taller, center the points in the middle of the histogram bars)

Thanks,
Gary

**Comment by sibyl229** [comment]
Hi @gw3 Sorry about the delay. For quite a while I couldn't figure out what made the bar off-center, even though the x coordinates are correct. So I've been putting this one off, until I fixed the other critical bugs that I need to hot fix (to live site). It has been fixed on staging now: http://staging.wormbase.org/species/c_elegans/gene/WBGene00015146#1--10 The problem was mostly caused by the bar paddings that were set by default.

I changed all the label text colour to black, and increased the height of the figure.

The empty figure shouldn't be showing up now. The code doesn't check the species, now it only show the figure if and only if there's FPKM data. Is that okay?

Please let me know if there's anything else to fix. If everything is fine, I will ask Todd to apply these changes as hotfix to production.

**Comment by gw3** [comment]
Hi @sibyl229,

Many thanks for working on this.

It looks good except for the text box that appears when you mouse-over the histogram bars.
Most of these are OK, except for the text for stages 'EE' and 'LE' which sometimes are correct and sometimes show the text for the '720 mins' life-stage.

It depends how high up the graph the mouse is when you move from the '720 mins' stage to the 'EE' stage - if it is high, it is refreshed for 'EE' OK, it it is lower than the '720 mins' bar height, then the text window seems not to be refreshed, it just stays on the '720 mins' histogram bar.

This is probably a bug in the graphics library you used, so I don't expect a fix any time soon :-(

I think it is good to go into production.

**Comment by sibyl229** [comment]
Hi @gw3 thanks a lot for checking and double checking the graphs. Yeah I can reproduce the issue with the tooltip. It's quite a weird issue :( I will ask Todd to get the previous fix to production for now, and will take a look at this later and see if there's anything I can do.

**Pull request merged**
