### PR TITLE
Ontology browser

### PR DESCRIPTION
**Pull request by azurebrd**
Fixes https://github.com/WormBase/website/issues/5978

### CODE REVIEW

**Comment by mgrbyte** [comment]
About my activity here re/reviewers: Accidentally clicked the wrong thing, tried to restore to what it was originally. Sorry for the noise!

**Comment by sibyl229** [comment]
Hi @azurebrd your branch has other code that's not supposed to be merged. I think it's because you did `git branch ontology_browser` when you were on a feature branch (instead of staging branch). 

To fix this, you probably need to checkout staging branch (get latest code), then create a new branch based on staging, finally `git cherry-pick [commit-hash]` relevant commits to you new branch.

**Comment by azurebrd** [comment]
Whoops !  Thanks @sibyl229 ! Sorry, I haven't done stuff no the website in a while, and I lost track.  Do we checkout from staging for wormbase/website, but checkout from develop for datomic-to-catalyst or is that also from staging ?

I did a git checkout ontology_browser and it was out of date, so I mistakenly did a git merge develop instead of staging.  

I think we can close this pull request.  I don't think anyone else is working on the ontology_browser branch, so I think it can be deleted, but I could be wrong, not sure how to check if anyone else is using it and we should leave it.

**Comment by sibyl229** [comment]
No worries!
> On Nov 17, 2017, at 10:53 AM, Juancarlos Chan <notifications@github.com> wrote:
> 
> Whoops ! Thanks @sibyl229 <https://github.com/sibyl229> ! Sorry, I haven't done stuff no the website in a while, and I lost track. Do we checkout from staging for wormbase/website, but checkout from develop for datomic-to-catalyst or is that also from staging ?
> 
Yup, staging branch for wormbase/website; develop branch for datomic-to-catalyst

> I did a git checkout ontology_browser and it was out of date, so I mistakenly did a git merge develop instead of staging.
I think you were on my 262-js branch, when you make the branch.
> I think we can close this pull request. I don't think anyone else is working on the ontology_browser branch, so I think it can be deleted, but I could be wrong, not sure how to check if anyone else is using it and we should leave it.
> 
Deleting the github copy won’t affect the local copy a developer has. And how about you create a new PR on a new branch first, before we delete the old one? If you have trouble doing that, please let me know.

**Comment by azurebrd** [comment]
Oh, you're right.  I don't remember why I picked 262-js.  I think I was confused about the .js changes.  Thanks for clearing that up.

Cool (staging / develop)

Thanks, I see that you merged and deleted the new ontology_browser_solr_data branch + the old ontology_browser branch.

**Pull request closed without merging**
