### PR TITLE
gbrowse config files for WS249

### PR DESCRIPTION
**Pull request by tharris**

### CODE REVIEW

**Comment by scottcain** [comment]
Presumably the removed species will affect JBrowse too.

**Comment by epaule** [comment]
@scottcain Correct.

I mean, in theory we could run JBrowse off the ParaSite GFF3s. But I think that is for the far future, if at all.

**Comment by khowe** [comment]
One user made a point about the ParaSite genome browser (from Ensembl) being sub-standard. Part of his criticism was well-founded. I'd like to see JBrowse for all species in ParaSite (i.e. nearly 100 genomes), as a way of tightening the integration with WormBase central.  Probably the most efficient way to make that happen is for it to be done at Hinxton, with guidance from @scottcain . Something to talk about in LA perhaps.

**Comment by scottcain** [comment]
@khowe It would be pretty easy to take the build tools I've built and put in website-admin/jbrowse and automatically build JBrowse instances for your genomes.  We can chat about it this week. 

(/me chuckles at "Part of his criticism was well-founded")

**Comment by tharris** [comment]
(@scottcain the removed species should silently disappear. They will not be listed in the ALL_SPECIES.stats file)

**Pull request merged**
