### PR TITLE
the 246 gff lost the "locus" attribute for gene:landmark features, but h...

### PR DESCRIPTION
**Pull request by scottcain**
...as Alias instead

### CODE REVIEW

**Comment by khowe** [comment]
Hmm, not according to the WS246 GFF3 for C. elegans that I'm looking at (see below). Same is true for WS247. 

I	landmark	gene	146488	154850	.	-	.	ID=landmark:bli-3;locus=bli-3
I	landmark	gene	1176473	1189651	.	+	.	ID=landmark:smg-2;locus=smg-2
I	landmark	gene	2706883	2717549	.	+	.	ID=landmark:lin-17;locus=lin-17
I	landmark	gene	3798566	3805718	.	-	.	ID=landmark:unc-11;locus=unc-11

**Comment by scottcain** [comment]
When I got this:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS246/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS246.annotations-processed.gff3.gz

I see this:

I       landmark        gene    146488  154850  .       -       .       ID=landmark:bli-3;Alias=bli-3
I       landmark        gene    1176473 1189651 .       +       .       ID=landmark:smg-2;Alias=smg-2
I       landmark        gene    2706883 2717549 .       +       .       ID=landmark:lin-17;Alias=lin-17
I       landmark        gene    3798566 3805718 .       -       .       ID=landmark:unc-11;Alias=unc-11

That's a little odd, no?

**Comment by tharris** [comment]
This looks like an ongoing problem dating back to WS240 where the notation for these landmark entries changed or failed to conform to previous conventions.

I’ve reverted this change and will rebuild the database tonight.

Scott, these entries will look like this:

I landmark gene 146488 154850 . - . ID=landmark:bli-3;locus=bli-3
I landmark gene 1176473 1189651 . + . ID=landmark:smg-2;locus=smg-2
I landmark gene 2706883 2717549 . + . ID=landmark:lin-17;locus=lin-17
I landmark gene 3798566 3805718 . - . ID=landmark:unc-11;locus=unc-11

**Comment by khowe** [comment]
So...this is a difference between the annotations.gff3 file that is made by Hinxton, and the annotations-processed.gff3 file that is made by OICR as part of the staging for a new release. Looks like locus is being changed to Alias in the landmark lines by the latter. @tharris may know why. 

To be honest, I'm not sure why we need an annotations-processed.gff3 file at all. I know that the file contains a number of lines that are not needed by Gbrowse, and I understand why we don't want the overhead of loading them into the database. But can't the loading script filter them on the fly? And besides, it seems that the conversion script is doing more than simply filtering out lines. It's also changing attributes.

If the annotations-processed file really is needed for [G|J]browse, can we remove it from the FTP site? I recall a user asking recently what the difference between the two files is. I don't think the annotations-processed file should be exposed to the end-users.

**Comment by tharris** [comment]
The loading script is part of the bioperl package. I don’t think WormBase specific processing belongs there. We could preprocess with command line-fu and pipes but it’s handy to have a standalone script, too.

The processing script used to change many attributes, add entries, change hierarchy, etc. It was critical to getting the genome browser to function properly. Some attributes where attached to child features, some to parents, some not included at all that had to be dynamically extracted from other sources. The situation has improved and now the processing script is minimal. 

The reason the file HAS been maintained on the FTP site is because, in the past, it was radically different from that supplied by Hinton. Users wanting to replicate our genome browser needed the CSHL and later OICR version of the file. I don’t think this is the case anymore and so will remove it.

**Comment by scottcain** [comment]
OK, then this pull request should be rejected and bug https://github.com/WormBase/website/issues/3550 should be marked closed (after the database has been rebuilt and it's been verified that the landmark labels have come back).

**Comment by scottcain** [comment]
Darn it.  I did a separate commit in the branch now it's part of this pull request.  I hate git.

**Pull request merged**
