### PR TITLE
Update external_urls

### PR DESCRIPTION
**Pull request by vanaukenk**
Updating cgc URLs

### CODE REVIEW

**Comment by sibyl229** [comment]
Hi @vanaukenk is there an example I could use to test the CGC external link? Thank you!

**Comment by vanaukenk** [comment]
Hi @sibyl229 

Here are some WB pages with link outs to the CGC:

http://www.wormbase.org/resources/laboratory/CGC
http://www.wormbase.org/species/c_elegans/variation/WBVar00092514
http://www.wormbase.org/species/c_elegans/strain/RB1228

Let me know if you need more details.  Thx.

**Comment by sibyl229** [comment]
Hi @vanaukenk ,

Sorry about the delay. The linkouts to CGC strains is available on staging. Would you like to double check?

http://staging.wormbase.org/species/c_elegans/variation/WBVar00092514#02--3
http://staging.wormbase.org/species/c_elegans/strain/RB1228#02--10

The CGC website url on Lab Overview is getting its data from the database. Do you know who shall I contact about updating the data there? http://www.wormbase.org/resources/laboratory/CGC#07--10

Thanks!

**Comment by epaule** [comment]
I think the database objects are parked in GeneACeDB.

**Comment by sibyl229** [comment]
Thanks @epaule you are so fast :) The data updated needed for this one is the URL tag in the Laboratory model.

**Comment by vanaukenk** [comment]
@epaule - did you update the Laboratory object in GeneACeDB, or should we loop in @tuli ?

@sibyl229 - the link on the ?Variation page works fine.

I was wondering, though, if it makes sense to slightly re-arrange the links and text in the Origin widget on the ?Strain page.

Perhaps something like this:

Available From:  CGC, University of Minnesota, MN (this would link to the corresponding strain page at the CGC, e.g. https://cgc.umn.edu/strain/RB1228)
Visit the CGC home page (this would link to the CGC home page, https://cgc.umn.edu/)
(Ann E Rougvie) (link to http://staging.wormbase.org/resources/person/WBPerson540)
CGC at WB (link to the WB CGC page, http://staging.wormbase.org/resources/laboratory/CGC)


Thx.

**Comment by sibyl229** [comment]
Hi @vanaukenk I change the "Available from" display a little bit: http://staging.wormbase.org/species/c_elegans/strain/RB1228#02--10

I omitted CGC homepage link, because users can easily go from a CGC strain page to their homepage.

I also omitted the CGC WB lab page for now, because I feel it probably isn't what the user is looking for, when they are trying to figure out how to get a strain. But I can add it in if you think we should show that link, I can add it in as well.

What do you think? Thanks

**Comment by sibyl229** [comment]
@vanaukenk Thanks!

**Comment by epaule** [comment]
I wouldn't dare to touch GeneACeDB ;-)

**Pull request merged**
