### PR TITLE
Update saving options to allow graph up to 8000x8000 scaled to fit th…

### PR DESCRIPTION
**Pull request by azurebrd**
…e page

### CODE REVIEW

**Comment by sibyl229** [comment]
Hi @azurebrd your change works as described, but I noticed an issue that became more noticeable with this change. So basically the legend overlaps with the figure (see screenshot). Do you think it works to have the legend in a separate column by the figure? 
screen shot 2017-06-20 at 5 22 24 pm

**Comment by raymond91125** [comment]
Hum, this undesirable effect should only happen when the browser window is narrow. But the intend of the code change is about the export PNG function only, shouldn't affect the cytoscape or widget display.

**Comment by azurebrd** [comment]
Hi @sibyl229 .  I'll defer to @raymond91125 about how he wants it, but the existing phenotype graph display already has the legend in a div floating on top of the graph if the browser window is narrow enough.  The current cytoscape window size seemed like a good size before, when we first implemented it.  There's potentially so many things to display horizontally that it seemed more useful to have it bigger and let users resize their browser window if they could.

**Comment by sibyl229** [comment]
Hi @raymond91125 @azurebrd Yeah, I took the screenshot on my 13 inch labtop. I imagine the layout of this widget is copied from interaction widget, which I made a change recently (on staging) to have the legend on a separate column (hence not covering the figure). The change required for that was https://github.com/WormBase/website/pull/5679/files . I will merge this pull request now, and will leave it for the two of you to decide if the phenotype graphs needs to take the same approach. Cheers.

**Comment by raymond91125** [comment]
@sibyl229 Thanks. Your approach may indeed be useful to copy. However, when the browser's window gets narrow, the interaction graph still displays in a less than optimal way, it appears.
selection_020

**Pull request merged**
