### PR TITLE
Added specifically expressed genes to anatomy terms in ontology brows…

### PR DESCRIPTION
**Pull request by azurebrd**
…er widget.

### CODE REVIEW

**Comment by raymond91125** [comment]
This addition provides results of a query that several users have asked for, namely, "are there genes expressed only in a given tissue but nowhere else".  Query of a single anatomy term can take minutes to run. Thus we run queries for all terms per WS release, store results in a flat file and show them term-specifically in the widget.

**Comment by sibyl229** [comment]
Merged. Thanks @azurebrd @raymond91125

**Comment by sibyl229** [comment]
Hi @raymond91125 the ontology browser change has been deployed to staging site. Would you like to test it?

**Comment by raymond91125** [comment]
yes, it works, e.g. species/all/anatomy_term/WBbt:0005237

**Comment by raymond91125** [comment]
one line and a box at the bottom of ontology browser widget, btw.

**Comment by xdwang** [comment]
how and where to find the info? I am interested in having a look too.

**Comment by raymond91125** [comment]
@xdwang follow the example page WBbt:0005237 at staging, the line is at the bottom of ontology browser widget.

**Comment by xdwang** [comment]
@raymond91125 the problem is, I don't know how to get to WBbt:0005237 page. That brings back my another issue: if I don't know the anatomy term ontology, I will be very stuck to look for a a term using this ontology browser. Say if I don't know excretory canal is under anatomy, under extracellular component, where shall I start to look? since there is no search to pin point my term.

**Comment by raymond91125** [comment]
@xdwang here's the URL
'''
http://staging.caltech.edu/species/all/anatomy_term/WBbt:0005237
'''
if you go to wormbase front page, the top right search box, type in "excretory canal" and select "for any anatomy term", you'll be brought to the correct anatomy term page. is that not sufficient?

**Comment by xdwang** [comment]
@raymond91125  the site doesn't seem to be right. 
what if I want to know who's the parent or child of my term?

**Comment by xdwang** [comment]
@raymond91125 I got the site and see the ontology widget. sorry. please ignore my earlier questions.

**Pull request merged**
